Completed Ranking Algorithm for Daily Streak Leaderboard
qu8n/focusbeacon pull request #30
Opened 2024-09-30 19:31 UTC by brandonpham13

Created a function using Python & Pandas to generate a list of each user's leaderboard ranking based on their current daily streak.

2024-10-01 21:08 UTC, qu8n requested changes

2024-10-01 21:08 UTC, qu8n commented on api_utils/leaderboard.py
Looks great, thank you. Could we keep only the important comments and remove the rest? For example, the comment for `skip_rank` is helpful, while the commented-out print statement is not. [This](https://stackoverflow.blog/2021/12/23/best-practices-for-writing-code-comments/) is a great resource on code comment practices; I highly recommend it.

2024-10-02 04:12 UTC, brandonpham13 commented on api_utils/leaderboard.py
Good call out. Just cleaned up the comments.

2024-10-02 22:12 UTC, qu8n commented
Moved this PR to #31. I couldn't add commits to this PR as it was created from another user's `main` branch.

2024-10-02 22:12 UTC, closed without merging